/**
 * This file was generated by cmake, do NOT modify.
 */
#ifndef DUI_UIBUILDCONFIG_H_
#define DUI_UIBUILDCONFIG_H_

#define HAVE_STRICMP
/* #undef HAVE_STRCASECMP */

#endif  // !DUI_UIBUILDCONFIG_H_
